### ISSUE TITLE
Поправить генерацию URL

### ISSUE THREAD

**Issue by jpsbur** [testsys/ball#10]
Конкатенация не всегда подходит

**Comment by burunduk3** [comment]
Речь, видимо, про генерацию ссылок в сложных случаях: например, для `oauth`. Видимо, их стоит переделать на `urllib.parse.urlencode`.

**Comment by burunduk3** [comment]
А для внутренних ссылок есть http://flask.pocoo.org/docs/0.12/api/#flask.url_for.
