### ISSUE TITLE
Locks

### ISSUE THREAD

**Issue by jpsbur** [testsys/ball#4]
DB locks (or at least checks) required
Probably should switch to some other solution than mysql.

**Comment by jpsbur** [comment]
First step: make changes idempotent. Pass source state in request along with destination state.

**Comment by burunduk3** [comment]
As I know, `pymysql` and `cymysql` use `autocommit=False` by default, so every database connection is a separate transaction. We'll need commit after every page generation (now only for database updates) if we'll make database connection persist (now connection is closed after every page generation).

Other thing: we have to mark select queries with `FOR UPDATE` if we'll make further changes based on query result (for example, do not change state of balloon if it is already taken by other volunteer). Commit e1596623853a053c727daefeb0468e66bba94671 adds this in `update.py`.

**Comment by burunduk3** [comment]
Commit a21256f7d0a16e7324547dee65b59a286bdccf1e adds check in only critical modification: taking the balloon.
