### ISSUE TITLE
Замечания после кубка школьников 2016-05-22

### ISSUE THREAD

**Issue by burunduk3** [testsys/ball#6]
- import должен быть кнопкой на страничке или инструкцией в ожидаемом месте (сейчас это запустить `import.sh --init <id> <name>`, где `id` — следующий номер в базе данных, `name` — короткое имя контеста, например, `m160522`)
- баг: кириллица в названии контеста не смогла при импорте («`IX Кубок бла-бла-бла…`» превратился в «`IX`»)
- интеграция с vk и прочим: делать ссылки вместо «`vk:18465`», в идеале — с получением имени (из vk хотя бы).
- добавление новых пользователей (выдача прав) через интерфейс
- добавление цветов через интерфейс

**Comment by burunduk3** [comment]
А, вот ещё вспомнил.
- сводная табличка по задачам и общее количество: сданных задач, шариков в очереди

**Comment by jpsbur** [comment]
> import должен быть кнопкой на страничке или инструкцией в ожидаемом месте (сейчас это запустить import.sh --init <id> <name>, где id — следующий номер в базе данных, name — короткое имя контеста, например, m160522)

На самом деле, это будет URL для получения contest.dat.

> баг: кириллица в названии контеста не смогла при импорте («IX Кубок бла-бла-бла…» превратился в «IX»)

Само пофиксится в процессе перевода с bash на python.

Уже стало лучше в https://github.com/testsys/ball/commit/6845742b2d25d7f5e480475047e0494680138d03

**Comment by jpsbur** [comment]
Еще у тебя, @burunduk3, должны были появиться права на этот репозиторий

**Comment by burunduk3** [comment]
Ещё не хватает ссылки на монитор. Если принимать url для contest.dat (то есть, в нашем случае, ссылку на view.pl), переделать её в monitor.pl тяжеловато. Я бы принимал всё же id монитора (имя файла), и использовал view.pl для скачивания результатов, а ссылку с monitor.pl где-нибудь показывал.

**Comment by jpsbur** [comment]
Во-первых, в view.pl и так есть монитор. Во-вторых, можно его уж если очень хочется, генерировать.
И знание, что все мониторы расположены, например, на acm.math.spbu.ru, не очень хочется использовать.

**Comment by jpsbur** [comment]
Ссылка на view.pl добавлена в 1d277de.
Видимо, встроенный монитор тоже имеет смысл.

**Comment by burunduk3** [comment]
Ссылки на волонтёров в b278e69a29ad8b09198893704bf30a83e69ca448
(Правда, только ВК.)

**Comment by burunduk3** [comment]
Выдача прав в 827b58815d79e2115bf49624e1daa0a90cdb1823

**Comment by burunduk3** [comment]
Произвольный цвет для шариков в a461e8d4ac8170d70e11a3a35628917e6aedf918

**Comment by burunduk3** [comment]
Добавил чуть больше счётчиков в b7ce829fb072d2b6617fdc6e331b39ae64a919fc. Остальные пожелания есть в других issue.
